---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by LX.
--- DateTime: 2026/4/7 16:28
---
--优惠券ID
local voucherId=ARGV[1]
--用户ID
local userId=ARGV[2]
--数据Key
--库存Key
local stockKey='seckill:stock:'..voucherId
--订单Key
local orderKey='seckill:order:'..voucherId
--判断库存是否充足
if (tonumber(redis.call('get', stockKey)) <= 0) then
    --库存不足返回1 
    return 1
end
--判断用户是否下单过
if (redis.call('sismember', orderKey, userId) == 1) then
    --存在说明是重复下单返回2
    return 2
end
--库存减1
redis.call('incrby', stockKey,-1)
--用户下单记录
redis.call('sadd', orderKey, userId)
return 0